# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_upvotemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotemodel',
            name='has_upvote',
            field=models.BooleanField(default=False),
        ),
    ]
