# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20170721_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='has_upvote',
        ),
    ]
